site_name: Crossplane Workshop
site_url: https://alvsanand.github.io/crossplane-workshop/
site_author: Álvaro Santos Andrés
site_description: >-
  Learning material for my workshop about Crossplane

# Repository
repo_name: alvsanand/crossplane-workshop
repo_url: https://github.com/alvsanand/crossplane-workshop
edit_uri: ""


# Configuration
theme:
  name: "material"

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - attr_list
  - footnotes
  - meta

# Page tree
nav:
  - Home: index.md
  - Setup Crossplane: setup.md
  - Your first plane: your-first-plane.md