site_name: APIfy your infra with Crossplane
site_url: https://alvsanand.github.io/apify-your-infra-with-crossplane/
site_author: Álvaro Santos Andrés
site_description: >-
  Learning material for APIfy your infra with Crossplane

# Repository
repo_name: alvsanand/apify-your-infra-with-crossplane
repo_url: https://github.com/alvsanand/apify-your-infra-with-crossplane
edit_uri: ""

# Configuration
theme:
  name: "material"

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Overview: overview.md
  - Lab 1 - Setup: setup.md
  - Lab 2 - Know the basis: know-the-basis.md
  - Lab 3 - Implement GitOps: implement-gitops.md
